-- Run this in Supabase > SQL Editor.
-- TEMPORARY development policies. Replace anon access with authenticated employee policies after login is built.

alter table public.guests enable row level security;

drop policy if exists "dev read guests" on public.guests;
drop policy if exists "dev insert guests" on public.guests;
drop policy if exists "dev update guests" on public.guests;
drop policy if exists "dev delete guests" on public.guests;

create policy "dev read guests" on public.guests for select to anon using (true);
create policy "dev insert guests" on public.guests for insert to anon with check (true);
create policy "dev update guests" on public.guests for update to anon using (true) with check (true);
create policy "dev delete guests" on public.guests for delete to anon using (true);

alter table public.guests add column if not exists tag text default 'Regular';

create table if not exists public.sms_logs (
  id bigint generated by default as identity primary key,
  guest_id bigint references public.guests(id) on delete set null,
  campaign text not null,
  audience text default 'Single Guest',
  phone text,
  message text,
  status text not null default 'pending',
  twilio_sid text,
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.sms_logs enable row level security;
drop policy if exists "dev read sms logs" on public.sms_logs;
create policy "dev read sms logs" on public.sms_logs for select to anon using (true);

create index if not exists sms_logs_guest_id_idx on public.sms_logs(guest_id);
create index if not exists sms_logs_created_at_idx on public.sms_logs(created_at desc);
