-- ORA CRM: connect campaigns -> logs -> guests
-- Paste this entire file into Supabase SQL Editor and click Run.

create table if not exists public.sms_campaigns (
  id bigint generated by default as identity primary key,
  campaign_name text not null,
  audience text,
  message_template text,
  recipient_mode text,
  selected_group text,
  total_recipients integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.sms_campaigns add column if not exists campaign_name text;
alter table public.sms_campaigns add column if not exists audience text;
alter table public.sms_campaigns add column if not exists message_template text;
alter table public.sms_campaigns add column if not exists recipient_mode text;
alter table public.sms_campaigns add column if not exists selected_group text;
alter table public.sms_campaigns add column if not exists total_recipients integer not null default 0;
alter table public.sms_campaigns add column if not exists sent_count integer not null default 0;
alter table public.sms_campaigns add column if not exists failed_count integer not null default 0;
alter table public.sms_campaigns add column if not exists status text not null default 'draft';
alter table public.sms_campaigns add column if not exists created_at timestamptz not null default now();
alter table public.sms_campaigns add column if not exists completed_at timestamptz;

alter table public.sms_logs add column if not exists guest_id bigint references public.guests(id) on delete set null;
alter table public.sms_logs add column if not exists campaign_id bigint references public.sms_campaigns(id) on delete set null;
alter table public.sms_logs add column if not exists twilio_sid text;
alter table public.sms_logs add column if not exists error_message text;

create index if not exists sms_logs_guest_id_idx on public.sms_logs(guest_id);
create index if not exists sms_logs_campaign_id_idx on public.sms_logs(campaign_id);
create index if not exists sms_logs_created_at_idx on public.sms_logs(created_at desc);
create unique index if not exists sms_logs_twilio_sid_unique_idx on public.sms_logs(twilio_sid) where twilio_sid is not null;

-- Attach older logs to guests by normalized phone number.
update public.sms_logs
set guest_id = guests.id
from public.guests
where sms_logs.guest_id is null
  and regexp_replace(coalesce(sms_logs.phone, ''), '[^0-9]', '', 'g') =
      regexp_replace(coalesce(guests.phone, ''), '[^0-9]', '', 'g')
  and regexp_replace(coalesce(sms_logs.phone, ''), '[^0-9]', '', 'g') <> '';

alter table public.sms_campaigns enable row level security;
alter table public.sms_logs enable row level security;

drop policy if exists "dev read sms campaigns" on public.sms_campaigns;
drop policy if exists "dev insert sms campaigns" on public.sms_campaigns;
drop policy if exists "dev update sms campaigns" on public.sms_campaigns;
create policy "dev read sms campaigns" on public.sms_campaigns for select to anon using (true);
create policy "dev insert sms campaigns" on public.sms_campaigns for insert to anon with check (true);
create policy "dev update sms campaigns" on public.sms_campaigns for update to anon using (true) with check (true);

drop policy if exists "dev read sms logs" on public.sms_logs;
create policy "dev read sms logs" on public.sms_logs for select to anon using (true);
